"""
Debug script: prints the RAW, untruncated, unparsed output of the judge model
for the first 5 records that came back with null scores in your run.

Run this on the cluster the same way you ran RQ1_judge_codeqa.py (same env,
same srun/tmux setup). It loads the same judge model and tokenizer, builds
the same prompt, and just prints exactly what the model generates — no
JSON parsing, no truncation in the print statement.
"""

import json
import os
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

JUDGE_MODEL_ID = "Qwen/Qwen2.5-Coder-7B-Instruct"
INPUT_FILE     = "RQ1_generate_codeqa/filtered/llama3.2_3b_instruct_predictions.json"
HF_CACHE       = os.getenv("HF_HOME", "")
MAX_NEW_TOKENS = 128

# IDs of records that came back null in your judged output.
# Edit this list if you want to debug different ones.
DEBUG_IDS = ["q1", "q2", "q3", "q4", "q5"]

SYSTEM_PROMPT = """You are an expert software engineer and code evaluator with deep experience assessing the quality of answers to source code comprehension questions.

You will be given a code snippet, a question about that code, a reference answer, and a predicted answer.
Your task is to evaluate the predicted answer across four dimensions: Accuracy, Completeness, Clarity, and Relevance.

Dataset context:
The questions come from CodeQA, a free-form question-answering benchmark built from real Python and Java code on GitHub.
Questions are derived from code comments (docstrings, Javadocs) and cover four types of code understanding:
- Functionality: what the code does, returns, creates, or produces
- Purpose: why the code exists or what problem it solves
- Property: attributes, parameters, types, conditions, or constraints in the code
- Workflow: how the code operates step-by-step or how data flows through it
Correct answers in CodeQA are typically concise — often a short phrase or a single sentence, not a paragraph.

Input sections:
<code>
The source code snippet to evaluate
</code>

<question>
The specific question about the code
</question>

<reference_answer>
The ground-truth answer for the question
</reference_answer>

<predicted_answer>
The answer generated by the model
</predicted_answer>

Respond ONLY with a valid JSON object in exactly this format:
{
  "accuracy":     {"score": <1-5>},
  "completeness": {"score": <1-5>},
  "clarity":      {"score": <1-5>},
  "relevance":    {"score": <1-5>}
}"""


def build_user_prompt(code, question, reference, prediction):
    return (
        f"Code:\n{code}\n\n"
        f"Question:\n{question}\n\n"
        f"Reference Answer:\n{reference}\n\n"
        f"Predicted Answer:\n{prediction}"
    )


print(f"CUDA available: {torch.cuda.is_available()}")
print(f"Loading judge: {JUDGE_MODEL_ID}")

tokenizer = AutoTokenizer.from_pretrained(
    JUDGE_MODEL_ID, cache_dir=HF_CACHE, trust_remote_code=True,
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    JUDGE_MODEL_ID,
    cache_dir=HF_CACHE,
    torch_dtype="auto",
    device_map="auto",
    trust_remote_code=True,
)
model.eval()
print(f"Model loaded on: {model.device}\n")

with open(INPUT_FILE, "r", encoding="utf-8") as f:
    dataset = json.load(f)

# build id -> index lookup the same way the main script assigns ids
records_by_id = {}
for i, item in enumerate(dataset):
    q_id = item.get("id", f"q{i+1}")
    records_by_id[q_id] = item

for q_id in DEBUG_IDS:
    item = records_by_id.get(q_id)
    if item is None:
        print(f"=== {q_id}: NOT FOUND IN INPUT FILE ===\n")
        continue

    code       = item.get("code", "")
    question   = item.get("question", "")
    reference  = item.get("answer", "")
    prediction = item.get("prediction", "")

    user_prompt = build_user_prompt(code, question, reference, prediction)
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user",   "content": user_prompt},
    ]

    formatted = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True,
    )

    inputs = tokenizer(
        formatted, return_tensors="pt", padding=True,
        truncation=True, max_length=8192,
    ).to(model.device)

    input_len = inputs["input_ids"].shape[1]
    print(f"=== {q_id} ===")
    print(f"Prompt token length: {input_len}")

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            use_cache=False,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    new_tokens = output_ids[0][input_len:]
    print(f"Generated token count: {new_tokens.shape[0]}")

    response = tokenizer.decode(new_tokens, skip_special_tokens=True)
    print("--- RAW DECODED OUTPUT (repr) ---")
    print(repr(response))
    print("--- RAW DECODED OUTPUT (printed) ---")
    print(response)
    print("=" * 60 + "\n")

print("Done.")
