
import json
import os
import torch
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM

JUDGE_MODEL_ID = "Qwen/Qwen2.5-Coder-7B-Instruct"
INPUT_FILE     = "RQ1_generate_codeqa/llama3.2_3b_instruct_predictions.json"
OUTPUT_JSON    = "RQ1_judge_codeqa/llama3.2_3b_instruct_judged1.json"
OUTPUT_CSV     = "RQ1_judge_codeqa/llama3.2_3b_instruct_judged1.csv"
OUTPUT_PLOT    = "RQ1_judge_codeqa/llama3.2_3b_instruct_judged1.png"
SAVE_EVERY     = 25
MAX_NEW_TOKENS = 128
HF_CACHE       = os.getenv("HF_HOME", "")

SYSTEM_PROMPT = """You are an expert software engineer and code evaluator with deep experience assessing the quality of answers to source code comprehension questions.

You will be given a code snippet, a question about that code, a reference answer, and a predicted answer.
Your task is to evaluate the predicted answer across four dimensions: Accuracy, Completeness, Clarity, and Relevance.

Dataset context:
The questions come from CodeQA, a free-form question-answering benchmark built from real Python and Java code on GitHub.
Questions are derived from code comments (docstrings, Javadocs) and cover four types of code understanding:
- Functionality: what the code does, returns, creates, or produces
- Purpose: why the code exists or what problem it solves
- Property: attributes, parameters, types, conditions, or constraints in the code
- Workflow: how the code operates step-by-step or how data flows through it
Correct answers in CodeQA are typically concise — often a short phrase or a single sentence, not a paragraph.

Input sections:
<code>
The source code snippet to evaluate
</code>

<question>
The specific question about the code
</question>

<reference_answer>
The ground-truth answer for the question
</reference_answer>

<predicted_answer>
The answer generated by the model
</predicted_answer>

Scoring dimensions (score each independently on a 1 to 5 integer scale):

ACCURACY — Does the predicted answer correctly match the reference answer's meaning and reflect what the code actually does?
  5: Completely correct — semantically equivalent to the reference answer and fully consistent with the code
  4: Mostly correct — minor factual slip or wording difference that does not change the core meaning
  3: Partially correct — captures something true but misses or misstates a key detail from the reference answer
  2: Mostly incorrect — contains a relevant element but is dominated by factual errors or gives the wrong specific reason
  1: Completely wrong — contradicts the reference answer/code, gives an unsupported reason, or addresses something entirely different

COMPLETENESS — Does the predicted answer cover everything the reference answer and question require?
  5: Fully complete — addresses everything the question asks at the right level of detail
  4: Mostly complete — minor omission that does not significantly affect the answer
  3: Partially complete — addresses part of the question but misses an important aspect
  2: Mostly incomplete — only a surface fragment of what is required is present
  1: Entirely incomplete — fails to address the question in any meaningful way

CLARITY — How clearly does the predicted answer communicate its point?
  5: Perfectly clear — unambiguous and easy to understand
  4: Mostly clear — minor phrasing awkwardness that does not impede understanding
  3: Somewhat clear — understandable with effort but awkwardly expressed
  2: Unclear — confusing or ambiguous to the point of impeding understanding
  1: Incomprehensible — incoherent, self-contradictory, or unreadable

RELEVANCE — Does the predicted answer directly target what the question and reference answer are asking for?
  5: Fully relevant — directly and precisely answers the exact question asked
  4: Mostly relevant — minor tangent that does not distract from the answer
  3: Partially relevant — discusses the same code but answers a related or different question
  2: Mostly irrelevant — misses the main point or specific reason asked by the question
  1: Completely irrelevant — does not address the question at all

IMPORTANT: Use the reference answer as the gold answer, but read the code carefully to understand and verify its meaning.
IMPORTANT: Semantic equivalence counts as correct. "the name", "Name of the user", and "it returns the user's name" can all be correct for the same question if they match the reference answer's meaning and the code supports them.
IMPORTANT: Score each dimension INDEPENDENTLY. A clear answer can still be inaccurate. An accurate statement can still be irrelevant if it does not answer the specific question.
IMPORTANT: A short answer is NOT incomplete if it fully addresses the question — CodeQA answers are intentionally concise.
IMPORTANT: Do NOT give a high score just because the predicted answer is fluent, clear, or grammatically correct.
IMPORTANT: Do NOT give a high score just because the predicted answer mentions something from the code.
IMPORTANT: Do NOT give a high Accuracy or Relevance score if the answer is only generally related to the code but misses what the question and reference answer specifically ask.
IMPORTANT: Do NOT infer missing reasoning that is not stated in the predicted answer.
IMPORTANT: If the question asks WHAT, the answer should identify the requested object, value, behavior, return value, or result.
IMPORTANT: If the question asks HOW, the answer should describe the correct process, mechanism, or workflow.
IMPORTANT: If the question asks WHY or FOR WHAT PURPOSE, the answer must give the correct specific cause, reason, purpose, or design rationale reflected in the reference answer and supported by the code.
IMPORTANT: If the question asks WHERE or WHEN, the answer should identify the correct location, condition, timing, or situation in the code.

WHY-QUESTION AND CAUSAL REASONING RULES:
Many difficult samples are WHY or PURPOSE questions.
For WHY questions, Accuracy depends on whether the predicted answer gives the correct specific cause, reason, or purpose asked by the question and reflected in the reference answer.
Do NOT give high Accuracy or Relevance scores to answers that are only generally related to the code but miss the specific reason.
Generic causal answers should be penalized when they do not identify the actual reason in the reference answer/code.
Repeated generic answers such as "because it will be handled by the parent process" should receive low Accuracy and low Relevance unless that exact explanation is clearly supported by the reference answer and code.
If the answer is clear but gives the wrong cause, Clarity may be high, but Accuracy and Relevance should be low.

CRITICAL: USE THE REFERENCE ANSWER AS THE GOLD ANSWER. Evaluate whether the predicted answer is semantically equivalent to the reference answer and supported by the code.
CRITICAL: DO NOT PENALIZE AN ANSWER FOR PHRASING OR VOCABULARY DIFFERENCES IF THE MEANING MATCHES THE REFERENCE ANSWER.
CRITICAL: DO NOT CONFLATE DIMENSIONS — score CLARITY independently of ACCURACY.
CRITICAL: DO NOT HALLUCINATE FACTS ABOUT THE CODE. If you are uncertain, score conservatively.
CRITICAL: DO NOT PRODUCE ANY TEXT OUTSIDE THE JSON OBJECT — no explanation, no preamble, no reasoning, no markdown.

Calibration examples:

Example 1 — fully correct, concise answer:
Code: def get_suite ( self , suite_dict , label = None ) : suite = unittest.TestSuite ( ) for test_name in suite_dict : suite.addTest ( self.get_test ( test_name ) ) return suite
Question: What does the code return?
Reference Answer: a test suite
Predicted Answer: a test suite
Output: {"accuracy": {"score": 5}, "completeness": {"score": 5}, "clarity": {"score": 5}, "relevance": {"score": 5}}

Example 2 — accurate but answers HOW instead of WHAT:
Code: def get_suite ( self , suite_dict , label = None ) : suite = unittest.TestSuite ( ) for test_name in suite_dict : suite.addTest ( self.get_test ( test_name ) ) return suite
Question: What does the code return?
Reference Answer: a test suite
Predicted Answer: It creates a new TestSuite object and iterates through the suite_dict to add each test by name before returning the populated suite object.
Output: {"accuracy": {"score": 5}, "completeness": {"score": 4}, "clarity": {"score": 5}, "relevance": {"score": 3}}

Example 3 — factually wrong but clearly written and partially on-topic:
Code: def is_valid_age ( age ) : return isinstance ( age , int ) and age >= 0 and age <= 120
Question: What does the code check?
Reference Answer: whether the age is an integer between 0 and 120
Predicted Answer: whether the input is a string
Output: {"accuracy": {"score": 1}, "completeness": {"score": 2}, "clarity": {"score": 5}, "relevance": {"score": 3}}

Example 4 — related to the code but does not answer the specific question:
Code: def save_file ( path , data ) : with open ( path , "w" ) as f : f.write ( data ) return True
Question: What does the function return?
Reference Answer: True
Predicted Answer: It writes data to a file at the given path.
Output: {"accuracy": {"score": 2}, "completeness": {"score": 2}, "clarity": {"score": 5}, "relevance": {"score": 3}}

Example 5 — WHY question with generic or unsupported reasoning:
Code: def cleanup ( parent , child ) : if child.parent == parent : parent.remove ( child )
Question: Why does the code check whether child.parent equals parent?
Reference Answer: to make sure the child belongs to that parent before removing it
Predicted Answer: because it will be handled by the parent process
Output: {"accuracy": {"score": 2}, "completeness": {"score": 2}, "clarity": {"score": 4}, "relevance": {"score": 2}}

Example 6 — WHY question with correct specific reason:
Code: def cleanup ( parent , child ) : if child.parent == parent : parent.remove ( child )
Question: Why does the code check whether child.parent equals parent?
Reference Answer: to make sure the child belongs to that parent before removing it
Predicted Answer: It verifies that the child is actually associated with the given parent before calling remove.
Output: {"accuracy": {"score": 5}, "completeness": {"score": 5}, "clarity": {"score": 5}, "relevance": {"score": 5}}

Respond ONLY with a valid JSON object in exactly this format:
{
  "accuracy":     {"score": <1-5>},
  "completeness": {"score": <1-5>},
  "clarity":      {"score": <1-5>},
  "relevance":    {"score": <1-5>}
}"""

def build_user_prompt(code, question, reference, prediction):
    return (
        f"Code:\n{code}\n\n"
        f"Question:\n{question}\n\n"
        f"Reference Answer:\n{reference}\n\n"
        f"Predicted Answer:\n{prediction}"
    )


def save_append(path, new_data):
    try:
        with open(path, "r", encoding="utf-8") as f:
            existing = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        existing = []
    existing_map = {item.get("id"): item for item in existing}
    for item in new_data:
        existing_map[item.get("id")] = item 
    combined = list(existing_map.values())
    with open(path, "w", encoding="utf-8") as f:
        json.dump(combined, f, indent=2, ensure_ascii=False)

def extract_scores(response_text):
    try:
        start = response_text.find("{")
        end   = response_text.rfind("}") + 1
        if start != -1 and end > start:
            parsed = json.loads(response_text[start:end])
        else:
            parsed = json.loads(response_text)
    except json.JSONDecodeError:
        print(f"  Parse error: {response_text[:200]}")
        return {}
    results = {}
    for metric, details in parsed.items():
        if isinstance(details, dict):
            score = details.get("score")
            if isinstance(score, int) and 1 <= score <= 5:
                results[metric] = {"score": score}
    return results

def export_csv(records, path):
    df = pd.DataFrame(records)
    cols = ["id", "dataset", "category", "code", "question",
            "answer", "prediction", "accuracy", "completeness",
            "clarity", "relevance"]
    df = df[[c for c in cols if c in df.columns]]
    df.to_csv(path, index=False)
    print(f"CSV saved to {path}")

def visualize(records, path):
    df = pd.DataFrame(records)
    metrics = ["accuracy", "completeness", "clarity", "relevance"]
    avgs, stds = [], []
    for m in metrics:
        valid = pd.to_numeric(df[m], errors="coerce").dropna()
        avgs.append(valid.mean() if len(valid) > 0 else 0)
        stds.append(valid.std()  if len(valid) > 1 else 0)
    plt.figure(figsize=(8, 5))
    plt.bar(metrics, avgs, yerr=stds, capsize=5,
            color="skyblue", edgecolor="black")
    plt.title("Average Judge Scores per Dimension — CodeQA")
    plt.ylabel("Score (1–5)")
    plt.ylim(1, 5)
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight")
    print(f"Plot saved to {path}")

print(f"CUDA available: {torch.cuda.is_available()}")
print(f"Device count:   {torch.cuda.device_count()}")
print(f"Loading judge:  {JUDGE_MODEL_ID}")

tokenizer = AutoTokenizer.from_pretrained(
    JUDGE_MODEL_ID,
    cache_dir=HF_CACHE,
    trust_remote_code=True,
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    JUDGE_MODEL_ID,
    cache_dir=HF_CACHE,
    torch_dtype="auto",     
    device_map="auto",
    trust_remote_code=True,
)
model.eval()
print(f"Model loaded on: {model.device}\n")

with open(INPUT_FILE, "r", encoding="utf-8") as f:
    dataset = json.load(f)
print(f"Loaded {len(dataset)} records from {INPUT_FILE}\n")

results     = []
csv_records = []

for i, item in enumerate(tqdm(dataset, desc="Judging")):
    code       = item.get("code", "")
    question   = item.get("question", "")
    reference  = item.get("answer", "")
    prediction = item.get("prediction", "")
    category   = item.get("category", "unknown")
    q_id       = item.get("id", f"q{i+1}")

    user_prompt = build_user_prompt(code, question, reference, prediction)

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user",   "content": user_prompt},
    ]

    try:
        formatted = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
    except Exception:
        formatted = (
            f"### System:\n{SYSTEM_PROMPT}\n\n"
            f"### User:\n{user_prompt}\n\n"
            f"### Assistant:\n"
        )

    inputs = tokenizer(
        formatted,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=8192,        
    ).to(model.device)

    try:
        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                do_sample=False,
                use_cache=False,                   
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
        new_tokens = output_ids[0][inputs["input_ids"].shape[1]:]
        response   = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
        scores     = extract_scores(response)
        if not scores:
            print(f"  Warning: no scores parsed at record {i+1}. Raw response: {response[:200]}")
    except Exception as e:
        print(f"  Error at record {i+1}: {e}")
        scores = {}

    acc  = scores.get("accuracy",     {}).get("score", None)
    comp = scores.get("completeness", {}).get("score", None)
    clar = scores.get("clarity",      {}).get("score", None)
    rel  = scores.get("relevance",    {}).get("score", None)

    print(f"[{i+1}/{len(dataset)}] category={category}")
    print(f"  acc={acc} comp={comp} clar={clar} rel={rel}\n")

    result = {
        "id":           q_id,
        "dataset":      "codeqa",
        "category":     category,
        "code":         code,
        "question":     question,
        "answer":       reference,
        "prediction":   prediction,
        "accuracy":     acc,
        "completeness": comp,
        "clarity":      clar,
        "relevance":    rel,
    }
    results.append(result)

    csv_records.append({
        "id":           q_id,
        "dataset":      "codeqa",
        "category":     category,
        "code":         code,
        "question":     question,
        "answer":       reference,
        "prediction":   prediction,
        "accuracy":     acc,
        "completeness": comp,
        "clarity":      clar,
        "relevance":    rel,
    })

    if (i + 1) % SAVE_EVERY == 0 or (i + 1) == len(dataset):
        save_append(OUTPUT_JSON, results)
        print(f"  Checkpoint saved at record {i+1}")
        results = []

export_csv(csv_records, OUTPUT_CSV)
visualize(csv_records, OUTPUT_PLOT)
print(f"\nDone. Results saved to {OUTPUT_JSON}")
